
name: "Multi event pipeline / workflow"
on:
    push:
        branches:
            - main


jobs:
    on-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Running on master push"
              run: echo "running on master push"

              
